feat: :sparkles: Categories Horizontal list view
DeltaTeam-UCAB/gymnastic-center-mobile pull request #55
Opened 2024-06-08 20:32 UTC by GianPX

Functionality uncomplete

2024-06-08 20:44 UTC, Alejo-FM reviewed
Muy bien aprovecha ahorita mismo y agrega:

- Repositorio y Datasource para obtener las categorias
- Un Bloc para poder manejarlo
- Y una pantalla donde nuestros usuarios puedan ver todas las categorias ya luego para donde lo redirige veremos xd

2024-06-09 02:29 UTC, GianPX commented
Categories Bloc added

2024-06-09 03:22 UTC, Alejo-FM requested changes
Buen trabajo, haz esos leves cambios que te menciono y hacemos merge

2024-06-09 03:22 UTC, Alejo-FM commented on lib/application/categories/bloc/categories_bloc.dart
> +        page: state.page + state.perPage));
Debes cambiar la linea 25 porque si lo haces así te estas saltando varias paginas, realmente lo que debes hacer es:

`page: state.page + 1`

porque cada pagina tiene la cantidad que le indiques entonces lo que haces ahi por ejemplo es saltar de la pagina 1 a varias por delante saltandote contenido

2024-06-09 03:22 UTC, Alejo-FM commented on lib/infrastructure/datasources/categories/categories_datasource_impl.dart
> +  CategoriesDatasourceImpl(KeyValueStorageService keyValueStorageI)
En esta parte del codigo haz unos leves cambios.

1. En el baseUrl pon: `baseUrl: '${Environment.backendApi}/category' ` , de esta forma no colocas eso a cada petición
2. En el constructor pon this.keyValueStorage es mas practico y mas gustoso al leer

2024-06-09 03:51 UTC, Alejo-FM approved these changes
Keep up the good work 🔥

2024-06-10 01:36 UTC, merged